In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("data/lean_dataset.csv")
df['issue_d'] = pd.to_datetime(df['issue_d'])

df = df[df['issue_d'] >= '2013-01-01']

df.head()

C:\Users\User\AppData\Local\Temp\ipykernel_29016\1905380788.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['issue_d'] = pd.to_datetime(df['issue_d'])

,loan_amnt,term,installment,emp_title,emp_length,home_ownership,annual_inc,issue_d,loan_status,purpose,...,avg_cur_bal,bc_util,chargeoff_within_12_mths,mo_sin_old_rev_tl_op,mort_acc,num_actv_bc_tl,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,target
0,4500,36 months,147.99,Accounts Examiner III,10+ years,RENT,38500.0,2018-12-01,Fully Paid,credit_card,...,2428.0,28.9,0.0,69.0,0.0,3.0,0.0,4.0,91.7,0
1,20000,60 months,507.55,Front office Lead,4 years,RENT,57000.0,2018-12-01,Fully Paid,debt_consolidation,...,3336.0,50.4,0.0,284.0,1.0,4.0,0.0,2.0,100.0,0
2,6600,36 months,217.05,Sewell collision center,10+ years,RENT,45000.0,2018-12-01,Fully Paid,credit_card,...,4473.0,58.2,0.0,108.0,0.0,2.0,0.0,0.0,84.6,0
3,2500,36 months,84.92,Manager,5 years,RENT,42000.0,2018-12-01,Fully Paid,other,...,6216.0,31.6,0.0,177.0,0.0,2.0,0.0,1.0,83.3,0
4,4000,36 months,144.55,service advisor,5 years,MORTGAGE,60000.0,2018-12-01,Fully Paid,house,...,9687.0,9.1,0.0,31.0,2.0,2.0,0.0,4.0,88.2,0

In [55]:
print(f"{len(df):_}")
summary = pd.DataFrame({
    'Unique Values': df.nunique(),
    'Data Type': df.dtypes,
    'Missing Values': df.isnull().sum(),
    'Missing %': (df.isnull().sum() / len(df) * 100).round(2),
    'Zeros Count': (df == 0).sum(),
    'Zeros %': ((df == 0).sum() / len(df) * 100).round(2)
})
summary

1_187_240

,Unique Values,Data Type,Missing Values,Missing %,Zeros Count,Zeros %
loan_amnt,1540,int64,0,0.00,0,0.00
term,2,object,0,0.00,0,0.00
installment,78211,float64,0,0.00,0,0.00
emp_length,12,object,0,0.00,0,0.00
home_ownership,3,object,0,0.00,0,0.00
annual_inc,58681,float64,0,0.00,0,0.00
issue_d,72,datetime64[ns],0,0.00,0,0.00
loan_status,3,object,0,0.00,0,0.00
purpose,14,object,0,0.00,0,0.00
dti,4786,float64,0,0.00,547,0.05
delinq_2yrs,30,float64,0,0.00,952024,80.19
earliest_cr_line,734,datetime64[ns],0,0.00,0,0.00
inq_last_6mths,7,float64,1,0.00,683689,57.59
mths_since_last_delinq,163,float64,588679,49.58,1245,0.10
open_acc,84,float64,0,0.00,11,0.00
pub_rec,37,float64,0,0.00,974000,82.04
revol_bal,80990,int64,0,0.00,4714,0.40
revol_util,1272,float64,0,0.00,5137,0.43
total_acc,142,float64,0,0.00,0,0.00
initial_list_status,2,object,0,0.00,0,0.00
application_type,1,object,0,0.00,0,0.00
acc_now_delinq,8,float64,0,0.00,1181163,99.49
tot_coll_amt,12613,float64,0,0.00,1003208,84.50
tot_cur_bal,387981,float64,0,0.00,312,0.03
total_rev_hi_lim,24853,float64,0,0.00,526,0.04
inq_fi,30,float64,710636,59.86,231061,19.46
inq_last_12m,43,float64,710637,59.86,113478,9.56
avg_cur_bal,75165,float64,19,0.00,304,0.03
bc_util,1432,float64,0,0.00,13613,1.15
chargeoff_within_12_mths,11,float64,0,0.00,1176924,99.13
mo_sin_old_rev_tl_op,751,float64,0,0.00,0,0.00
mort_acc,38,float64,0,0.00,477810,40.25
num_actv_bc_tl,34,float64,0,0.00,24740,2.08
num_tl_90g_dpd_24m,29,float64,0,0.00,1118475,94.21
num_tl_op_past_12m,32,float64,0,0.00,197907,16.67
pct_tl_nvr_dlq,626,float64,154,0.01,3,0.00
target,2,int64,0,0.00,945604,79.65
emp_length_alt,3,object,69106,5.82,0,0.00
has_delinq_flag,2,int64,0,0.00,952024,80.19
num_tl_90g_dpd_24m_flag,2,int64,0,0.00,1118475,94.21
mo_sin_old_cr_line,718,int32,0,0.00,0,0.00
data_gap_flag,1,int64,0,0.00,1187240,100.00
revol_util_custom,7,category,0,0.00,0,0.00
bc_util_custom,7,category,0,0.00,0,0.00
inq_fi_6m_binned,4,category,1,0.00,0,0.00
inq_fi_6m_binned_2,2,category,1,0.00,0,0.00
has_recent_chargeoff,2,int64,0,0.00,1176924,99.13

In [5]:
df_missing_inq = df[df["inq_fi"].isna()].copy()
summary = pd.DataFrame({
    'Unique Values': df_missing_inq.nunique(),
    'Data Type': df_missing_inq.dtypes,
    'Missing Values': df_missing_inq.isnull().sum(),
    'Missing %': (df_missing_inq.isnull().sum() / len(df_missing_inq) * 100).round(2),
    'Zeros Count': (df_missing_inq == 0).sum(),
    'Zeros %': ((df_missing_inq == 0).sum() / len(df_missing_inq) * 100).round(2)
})
summary

,Unique Values,Data Type,Missing Values,Missing %,Zeros Count,Zeros %
loan_amnt,1361,int64,0,0.00,0,0.00
term,2,object,0,0.00,0,0.00
installment,60016,float64,0,0.00,0,0.00
emp_title,227112,object,42064,5.92,0,0.00
emp_length,11,object,38243,5.38,0,0.00
home_ownership,4,object,0,0.00,0,0.00
annual_inc,41736,float64,0,0.00,0,0.00
issue_d,37,datetime64[ns],0,0.00,0,0.00
loan_status,2,object,0,0.00,0,0.00
purpose,14,object,0,0.00,0,0.00
dti,4000,float64,0,0.00,190,0.03
delinq_2yrs,29,float64,0,0.00,569455,80.13
earliest_cr_line,692,object,0,0.00,0,0.00
inq_last_6mths,7,float64,0,0.00,400848,56.41
mths_since_last_delinq,155,float64,356201,50.12,796,0.11
open_acc,76,float64,0,0.00,7,0.00
pub_rec,30,float64,0,0.00,590328,83.07
revol_bal,68395,int64,0,0.00,1842,0.26
revol_util,1244,float64,333,0.05,2012,0.28
total_acc,133,float64,0,0.00,0,0.00
initial_list_status,2,object,0,0.00,0,0.00
application_type,1,object,0,0.00,0,0.00
acc_now_delinq,8,float64,0,0.00,706999,99.49
tot_coll_amt,9803,float64,0,0.00,607694,85.51
tot_cur_bal,303906,float64,0,0.00,108,0.02
total_rev_hi_lim,18677,float64,0,0.00,250,0.04
inq_fi,0,float64,710636,100.00,0,0.00
inq_last_12m,0,float64,710636,100.00,0,0.00
avg_cur_bal,64963,float64,12,0.00,98,0.01
bc_util,1381,float64,7173,1.01,6536,0.92
chargeoff_within_12_mths,10,float64,0,0.00,704364,99.12
mo_sin_old_rev_tl_op,728,float64,0,0.00,0,0.00
mort_acc,37,float64,0,0.00,282188,39.71
num_actv_bc_tl,30,float64,0,0.00,12769,1.80
num_tl_90g_dpd_24m,25,float64,0,0.00,668871,94.12
num_tl_op_past_12m,28,float64,0,0.00,124111,17.46
pct_tl_nvr_dlq,556,float64,153,0.02,0,0.00
target,2,int64,0,0.00,577142,81.21

In [6]:
print(df_missing_inq["issue_d"].sort_index(ascending=False).unique())
print(df[df["issue_d"].dt.year > 2016]["issue_d"].sort_index(ascending=False).unique())
print(len(df[df["issue_d"].dt.year > 2016]))

<DatetimeArray>
['2014-01-01 00:00:00', '2014-02-01 00:00:00', '2014-03-01 00:00:00',
 '2014-04-01 00:00:00', '2014-05-01 00:00:00', '2014-06-01 00:00:00',
 '2014-07-01 00:00:00', '2014-08-01 00:00:00', '2014-09-01 00:00:00',
 '2014-10-01 00:00:00', '2014-11-01 00:00:00', '2014-12-01 00:00:00',
 '2013-01-01 00:00:00', '2013-02-01 00:00:00', '2013-03-01 00:00:00',
 '2013-04-01 00:00:00', '2013-05-01 00:00:00', '2013-06-01 00:00:00',
 '2013-07-01 00:00:00', '2013-08-01 00:00:00', '2013-09-01 00:00:00',
 '2013-10-01 00:00:00', '2013-11-01 00:00:00', '2013-12-01 00:00:00',
 '2015-01-01 00:00:00', '2015-02-01 00:00:00', '2015-03-01 00:00:00',
 '2015-04-01 00:00:00', '2015-05-01 00:00:00', '2015-06-01 00:00:00',
 '2015-07-01 00:00:00', '2015-08-01 00:00:00', '2015-09-01 00:00:00',
 '2015-10-01 00:00:00', '2015-11-01 00:00:00', '2015-12-01 00:00:00',
 '2016-01-01 00:00:00']
Length: 37, dtype: datetime64[ns]
<DatetimeArray>
['2017-10-01 00:00:00', '2017-11-01 00:00:00', '2017-12-01 00:00:00',
 '2017-04-01 00:00:00', '2017-05-01 00:00:00', '2017-06-01 00:00:00',
 '2017-07-01 00:00:00', '2017-08-01 00:00:00', '2017-09-01 00:00:00',
 '2017-01-01 00:00:00', '2017-02-01 00:00:00', '2017-03-01 00:00:00',
 '2018-01-01 00:00:00', '2018-02-01 00:00:00', '2018-03-01 00:00:00',
 '2018-04-01 00:00:00', '2018-05-01 00:00:00', '2018-06-01 00:00:00',
 '2018-07-01 00:00:00', '2018-08-01 00:00:00', '2018-09-01 00:00:00',
 '2018-10-01 00:00:00', '2018-11-01 00:00:00', '2018-12-01 00:00:00']
Length: 24, dtype: datetime64[ns]
188166

Missing values mostly vanished when standards had risen.

In [7]:
# emp_title missings: 148559  |  emp_length missings: 130357
missing_both = (df['emp_length'].isna() & df['emp_title'].isna()).sum()
print("Missing both:", missing_both) # Potential jobless

missing_both_with_income = (df['emp_length'].isna() & df['emp_title'].isna() & (df["annual_inc"] > 1000)).sum()
print("Missing but with income:", missing_both_with_income) # With income

missing_length_but_income = (df["emp_length"].isna() & (df["annual_inc"] < 1000)).sum()
print("Missing length but without income", missing_length_but_income)

missing_title_but_income = (df["emp_title"].isna() & (df["annual_inc"] < 1000)).sum()
print("Missing title but without income", missing_title_but_income)

Missing both: 68627
Missing but with income: 68627
Missing length but without income 0
Missing title but without income 0

In [8]:
df.drop(columns=["emp_title"], inplace=True)

## WoE and VIF

In [9]:
def calculate_woe(df, feature, target="target"):
    stats = df.groupby(feature)[target].agg(["count", "sum"])
    stats.columns = ["total", "bad"]
    stats["good"] = stats["total"] - stats["bad"]

    perc_bad = (stats['bad'] +0.5) / (stats['bad'].sum())
    perc_good = (stats['good'] +0.5)/ (stats['good'].sum())
    
    stats['WoE'] = np.log(perc_good / perc_bad)
    stats['IV'] = (perc_good - perc_bad) * stats['WoE']

    total_IV = stats["IV"].sum()
    print(f"\n\nIV for {feature} = {total_IV:.4f}\n\n")
    
    return stats.sort_values('WoE'), total_IV

In [10]:
def check_num_bins(df: pd.DataFrame, col: str, target_col: str = "target", start: int = 2, end: int = 10) -> int:
    is_numeric = pd.api.types.is_numeric_dtype(df[col])
    
    if not is_numeric:
        print(f"Analiza zmiennej nienumerycznej: {col}")
        temp_df = df[[col, target_col]].copy()
        temp_df[col] = temp_df[col].fillna("MISSING").astype(str)
        
        print(calculate_woe(temp_df, col)[0])
    else:
        best_IV = 0
        print(f"Analiza zmiennej numerycznej: {col}")

        for bin_num in range(start, end):
            temp_df = df[[col, target_col]].copy()
            
            try:
                temp_df[f'{col}_bins'] = pd.qcut(
                    temp_df[col], 
                    q=bin_num, 
                    duplicates='drop'
                ).astype(str)
                actual_bins = temp_df[f'{col}_bins'].nunique()
                
                print(f"\n_____________ Liczba żądanych binów: {bin_num} (Faktycznie: {actual_bins}) _____________")
                
                result = calculate_woe(temp_df, f"{col}_bins")
                best_IV = result[1]
                print(result[0])
                
                
                if actual_bins < bin_num:
                    print(f"Osiągnięto maksymalny podział dla wartości unikalnych przy {actual_bins} binach.")
                    break
                    
            except ValueError as e:
                print(f"Błąd przy {bin_num} binach: {e}")
                continue
        if best_IV < 0.02:
            print("Zmienna o za niskiej wartości informacyjnej.")

# emp_length

In [11]:
df["emp_length"] = df["emp_length"].fillna("Missing")
check_num_bins(df, "emp_length")

Analiza zmiennej nienumerycznej: emp_length


IV for emp_length = 0.0116


             total    bad    good       WoE            IV
emp_length
Missing      69106  18694   50412 -0.372383  8.957270e-03
1 year       77699  16450   61249 -0.049793  1.646572e-04
< 1 year     90782  18963   71819 -0.032753  8.282353e-05
3 years      94806  19414   75392 -0.007705  4.751432e-06
2 years     106832  21783   85049 -0.002312  4.812579e-07
4 years      69495  14169   55326 -0.002232  2.918709e-07
8 years      54727  11149   43578 -0.001223  6.899780e-08
9 years      45782   9314   36468  0.000484  9.035035e-09
5 years      72710  14668   58042  0.011081  7.494904e-06
6 years      54221  10765   43456  0.031021  4.354604e-05
7 years      52698  10450   42248  0.032527  4.650865e-05
10+ years   398383  75817  322566  0.083588  2.286493e-03

In [12]:
df["emp_length_alt"] = df["emp_length"].map({
    "1 year": "0-3",
    "< 1 year": "0-3",
    "2 years": "0-3",
    "3 years": "0-3",
    "4 years": "4-9",
    "5 years": "4-9",
    "6 years": "4-9",
    "7 years": "4-9",
    "8 years": "4-9",
    "9 years": "4-9",
    "10+ years": "10+",
})

calculate_woe(df, "emp_length_alt")

IV for emp_length_alt = 0.0020

(                 total    bad    good       WoE        IV
 emp_length_alt
 0-3             370119  76610  293509 -0.046952  0.000740
 4-9             349633  70515  279118 -0.014324  0.000064
 10+             398383  75817  322566  0.057852  0.001172,
 np.float64(0.001976232655292477))

### WoE for emp_length = 0.01

Chance to delete feature for good, but maybe change to one column "is_missing"

# loan_amnt

In [13]:
check_num_bins(df, "loan_amnt")

Analiza zmiennej numerycznej: loan_amnt

_____________ Liczba żądanych binów: 2 (Faktycznie: 2) _____________


IV for loan_amnt_bins = 0.0244


                     total     bad    good       WoE        IV
loan_amnt_bins
(12000.0, 40000.0]  588061  134686  453375 -0.150622  0.011739
(999.999, 12000.0]  599180  106950  492230  0.162189  0.012640

_____________ Liczba żądanych binów: 3 (Faktycznie: 3) _____________


IV for loan_amnt_bins = 0.0297


                     total    bad    good       WoE        IV
loan_amnt_bins
(16800.0, 40000.0]  394163  91654  302509 -0.170306  0.010116
(9900.0, 16800.0]   396969  84016  312953 -0.049351  0.000826
(999.999, 9900.0]   396109  65966  330143  0.245988  0.018728

_____________ Liczba żądanych binów: 4 (Faktycznie: 4) _____________


IV for loan_amnt_bins = 0.0308


                     total    bad    good       WoE        IV
loan_amnt_bins
(20000.0, 40000.0]  259204  61161  198043 -0.189424  0.008274
(12000.0, 20000.0]  328857  73525  255332 -0.119458  0.004093
(8000.0, 12000.0]   266291  52328  213963  0.043872  0.000426
(999.999, 8000.0]   332889  54622  278267  0.263745  0.017993

_____________ Liczba żądanych binów: 5 (Faktycznie: 5) _____________


IV for loan_amnt_bins = 0.0323


                     total    bad    good       WoE        IV
loan_amnt_bins
(21000.0, 40000.0]  236230  55722  180508 -0.188999  0.007506
(15000.0, 21000.0]  213286  49153  164133 -0.158660  0.004735
(10000.0, 15000.0]  252544  53873  198671 -0.059378  0.000763
(6700.0, 10000.0]   247684  44467  203217  0.155126  0.004790
(999.999, 6700.0]   237497  38421  199076  0.280680  0.014461

_____________ Liczba żądanych binów: 6 (Faktycznie: 6) _____________


IV for loan_amnt_bins = 0.0318


                     total    bad    good       WoE        IV
loan_amnt_bins
(24000.0, 40000.0]  176089  41554  134535 -0.189570  0.005630
(16800.0, 24000.0]  218074  50100  167974 -0.154611  0.004592
(12000.0, 16800.0]  193898  43032  150866 -0.109953  0.002039
(9900.0, 12000.0]   203071  40984  162087  0.010550  0.000019
(6000.0, 9900.0]    179077  31235  147842  0.190200  0.005151
(999.999, 6000.0]   217032  34731  182301  0.293622  0.014403

_____________ Liczba żądanych binów: 7 (Faktycznie: 7) _____________


IV for loan_amnt_bins = 0.0320


                     total    bad    good       WoE        IV
loan_amnt_bins
(25000.0, 40000.0]  140847  33834  107013 -0.212918  0.005718
(15000.0, 18850.0]  110310  25907   84403 -0.183316  0.003292
(18850.0, 25000.0]  198359  45134  153225 -0.142129  0.003517
(11000.0, 15000.0]  222306  47292  175014 -0.055875  0.000594
(8400.0, 11000.0]   171614  32743  138871  0.080452  0.000913
(5600.0, 8400.0]    170035  28767  141268  0.227024  0.006888
(999.999, 5600.0]   173770  27959  145811  0.287165  0.011053

_____________ Liczba żądanych binów: 8 (Faktycznie: 8) _____________


IV for loan_amnt_bins = 0.0328


                     total    bad    good       WoE        IV
loan_amnt_bins
(25000.0, 40000.0]  140847  33834  107013 -0.212918  0.005718
(20000.0, 25000.0]  118357  27327   91030 -0.161091  0.002711
(15400.0, 20000.0]  185863  42439  143424 -0.146663  0.003514
(12000.0, 15400.0]  142994  31086  111908 -0.083485  0.000860
(10000.0, 12000.0]  113999  24062   89937 -0.045932  0.000205
(8000.0, 10000.0]   152292  28266  124026  0.114425  0.001623
(5000.0, 8000.0]    176204  29448  146756  0.241739  0.008056
(999.999, 5000.0]   156685  25174  131511  0.288870  0.010080

_____________ Liczba żądanych binów: 9 (Faktycznie: 9) _____________


IV for loan_amnt_bins = 0.0313


                     total    bad    good       WoE            IV
loan_amnt_bins
(26400.0, 40000.0]  131706  31514  100192 -0.207747  5.082611e-03
(20000.0, 26400.0]  127498  29647   97851 -0.170319  3.272611e-03
(16800.0, 20000.0]  134959  30493  104466 -0.133040  2.091406e-03
(14300.0, 16800.0]  133133  29422  103711 -0.104539  1.263494e-03
(11500.0, 14300.0]  130742  27531  103211 -0.042943  2.056654e-04
(9900.0, 11500.0]   133094  27063  106031  0.001158  1.502221e-07
(7200.0, 9900.0]    123690  21738  101952  0.181030  3.231993e-03
(5000.0, 7200.0]    115734  19054   96680  0.259716  6.073649e-03
(999.999, 5000.0]   156685  25174  131511  0.288870  1.007955e-02

### apparent trend for "loan_amnt", IV > 0.02

In [14]:
# IV Low for everything - collapsed None, Any and Other to Mortage
def home_owner(val):
    if val in ["RENT", "MORTGAGE"]:
        return val
    return "OWN_OTHER"


df["home_ownership"] = df["home_ownership"].apply(home_owner)
check_num_bins(df, "home_ownership")

Analiza zmiennej nienumerycznej: home_ownership


IV for home_ownership = 0.0349


                 total     bad    good       WoE        IV
home_ownership
RENT            469489  112106  357383 -0.205032  0.017634
OWN_OTHER       130673   27251  103422 -0.030678  0.000105
MORTGAGE        587079  102279  484800  0.191636  0.017134

# DTI

In [15]:
check_num_bins(df, 'dti')

Analiza zmiennej numerycznej: dti

_____________ Liczba żądanych binów: 2 (Faktycznie: 2) _____________


IV for dti_bins = 0.0523


                  total     bad    good       WoE        IV
dti_bins
(17.73, 49.96]   593408  142686  450722 -0.214191  0.024386
(-1.001, 17.73]  593833   98950  494883  0.245310  0.027928

_____________ Liczba żądanych binów: 3 (Faktycznie: 3) _____________


IV for dti_bins = 0.0653


                  total     bad    good       WoE        IV
dti_bins
(21.81, 49.96]   395467  102069  293398 -0.308515  0.034595
(13.93, 21.81]   395631   77222  318409  0.052255  0.000896
(-1.001, 13.93]  396143   62345  333798  0.313454  0.029774

_____________ Liczba żądanych binów: 4 (Faktycznie: 4) _____________


IV for dti_bins = 0.0695


                  total    bad    good       WoE        IV
dti_bins
(24.19, 49.96]   296577  79744  216833 -0.364090  0.036668
(17.73, 24.19]   296831  62942  233889 -0.051765  0.000680
(11.93, 17.73]   296776  53385  243391  0.152740  0.005569
(-1.001, 11.93]  297057  45565  251492  0.343870  0.026612

_____________ Liczba żądanych binów: 5 (Faktycznie: 5) _____________


IV for dti_bins = 0.0721


                  total    bad    good       WoE        IV
dti_bins
(25.8, 49.96]    237209  65567  171642 -0.402059  0.036118
(20.1, 25.8]     237535  53292  184243 -0.123930  0.003186
(15.45, 20.1]    237275  46341  190934  0.051500  0.000522
(10.63, 15.45]   237366  40509  196857  0.216551  0.008778
(-1.001, 10.63]  237856  35927  201929  0.362023  0.023481

_____________ Liczba żądanych binów: 6 (Faktycznie: 6) _____________


IV for dti_bins = 0.0733


                 total    bad    good       WoE        IV
dti_bins
(26.99, 49.96]  197616  55711  141905 -0.429418  0.034564
(21.81, 26.99]  197851  46358  151493 -0.180254  0.005704
(17.73, 21.81]  197941  40617  157324 -0.010281  0.000018
(13.93, 17.73]  197690  36605  161085  0.117344  0.002213
(9.67, 13.93]   197943  32649  165294  0.257507  0.010219
(-1.001, 9.67]  198200  29696  168504  0.371541  0.020546

_____________ Liczba żądanych binów: 7 (Faktycznie: 7) _____________


IV for dti_bins = 0.0740


                 total    bad    good       WoE        IV
dti_bins
(27.91, 49.96]  169602  48538  121064 -0.450426  0.032812
(23.13, 27.91]  169478  40927  128551 -0.219865  0.007350
(19.41, 23.13]  169398  36327  133071 -0.066081  0.000635
(16.1, 19.41]   169788  33078  136710  0.054590  0.000419
(12.8, 16.1]    169644  30194  139450  0.165657  0.003730
(8.93, 12.8]    169572  27299  142273  0.286490  0.010738
(-1.001, 8.93]  169759  25273  144486  0.379037  0.018271

_____________ Liczba żądanych binów: 8 (Faktycznie: 8) _____________


IV for dti_bins = 0.0749


                 total    bad    good       WoE        IV
dti_bins
(28.64, 49.96]  148403  43083  105320 -0.470524  0.031488
(24.19, 28.64]  148174  36661  111513 -0.251974  0.008515
(20.73, 24.19]  148267  32921  115346 -0.110578  0.001577
(17.73, 20.73]  148564  30021  118543  0.008974  0.000010
(14.88, 17.73]  148055  27908  120147  0.095396  0.001103
(11.93, 14.88]  148721  25477  123244  0.211982  0.005278
(8.33, 11.93]   148517  23468  125049  0.308658  0.010840
(-1.001, 8.33]  148540  22097  126443  0.379939  0.016059

_____________ Liczba żądanych binów: 9 (Faktycznie: 9) _____________


IV for dti_bins = 0.0751


                 total    bad    good       WoE        IV
dti_bins
(29.25, 49.96]  131829  38728   93101 -0.487278  0.030123
(25.06, 29.25]  131927  33217   98710 -0.275278  0.009106
(21.81, 25.06]  131711  30124  101587 -0.148811  0.002565
(19.03, 21.81]  131945  27539  104406 -0.031722  0.000113
(16.46, 19.03]  132105  25717  106388  0.055533  0.000338
(13.93, 16.46]  131581  23966  107615  0.137515  0.002011
(11.22, 13.93]  131891  22083  109808  0.239515  0.005924
(7.84, 11.22]   132154  20660  111494  0.321359  0.010414
(-1.001, 7.84]  132098  19602  112496  0.382873  0.014489

In [16]:
df[df["dti"] < 0]
# target 0, weird case, only one -> BE GONE!
df = df[df['dti'] >= 0].reset_index(drop=True) # Just to make index look pretty :)

In [17]:
df.head()

,loan_amnt,term,installment,emp_length,home_ownership,annual_inc,issue_d,loan_status,purpose,dti,...,bc_util,chargeoff_within_12_mths,mo_sin_old_rev_tl_op,mort_acc,num_actv_bc_tl,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,target,emp_length_alt
0,4500,36 months,147.99,10+ years,RENT,38500.0,2018-12-01,Fully Paid,credit_card,4.64,...,28.9,0.0,69.0,0.0,3.0,0.0,4.0,91.7,0,10+
1,20000,60 months,507.55,4 years,RENT,57000.0,2018-12-01,Fully Paid,debt_consolidation,22.18,...,50.4,0.0,284.0,1.0,4.0,0.0,2.0,100.0,0,4-9
2,6600,36 months,217.05,10+ years,RENT,45000.0,2018-12-01,Fully Paid,credit_card,16.21,...,58.2,0.0,108.0,0.0,2.0,0.0,0.0,84.6,0,10+
3,2500,36 months,84.92,5 years,RENT,42000.0,2018-12-01,Fully Paid,other,15.09,...,31.6,0.0,177.0,0.0,2.0,0.0,1.0,83.3,0,4-9
4,4000,36 months,144.55,5 years,MORTGAGE,60000.0,2018-12-01,Fully Paid,house,19.10,...,9.1,0.0,31.0,2.0,2.0,0.0,4.0,88.2,0,4-9

# Annual Income and Total Current Balance

In [18]:
print(df[['annual_inc', 'tot_cur_bal']].corr())

             annual_inc  tot_cur_bal
annual_inc     1.000000     0.396529
tot_cur_bal    0.396529     1.000000

In [19]:
check_num_bins(df, "annual_inc")

Analiza zmiennej numerycznej: annual_inc

_____________ Liczba żądanych binów: 2 (Faktycznie: 2) _____________


IV for annual_inc_bins = 0.0209


                        total     bad    good       WoE        IV
annual_inc_bins
(2399.999, 65000.0]    606685  137348  469337 -0.135591  0.009773
(65000.0, 10999200.0]  580555  104288  476267  0.154427  0.011130

_____________ Liczba żądanych binów: 3 (Faktycznie: 3) _____________


IV for annual_inc_bins = 0.0253


                        total    bad    good       WoE        IV
annual_inc_bins
(2399.999, 52000.0]    398602  92816  305786 -0.172129  0.010455
(52000.0, 80000.0]     395312  81761  313551 -0.020234  0.000137
(80000.0, 10999200.0]  393326  67059  326267  0.217746  0.014701

_____________ Liczba żądanych binów: 4 (Faktycznie: 4) _____________


IV for annual_inc_bins = 0.0274


                        total    bad    good       WoE        IV
annual_inc_bins
(2399.999, 46906.75]   296810  70470  226340 -0.197545  0.010327
(46906.75, 65000.0]    309875  66878  242997 -0.074218  0.001469
(65000.0, 92000.0]     288575  56012  232563  0.059197  0.000837
(92000.0, 10999200.0]  291980  48276  243704  0.254620  0.014751

_____________ Liczba żądanych binów: 5 (Faktycznie: 5) _____________


IV for annual_inc_bins = 0.0283


                         total    bad    good       WoE        IV
annual_inc_bins
(2399.999, 43000.0]     244195  58514  185681 -0.209633  0.009601
(43000.0, 58000.0]      236683  51983  184700 -0.096582  0.001913
(58000.0, 75000.0]      255929  52955  202974 -0.020763  0.000094
(75000.0, 100000.0]     224387  41885  182502  0.107433  0.002112
(100000.0, 10999200.0]  226046  36299  189747  0.289499  0.014602

_____________ Liczba żądanych binów: 6 (Faktycznie: 6) _____________


IV for annual_inc_bins = 0.0287


                         total    bad    good       WoE        IV
annual_inc_bins
(2399.999, 40000.0]     208215  50304  157911 -0.220451  0.009080
(40000.0, 52000.0]      190387  42512  147875 -0.117819  0.002304
(52000.0, 65000.0]      208083  44532  163551 -0.063483  0.000720
(65000.0, 80000.0]      187229  37229  150000  0.029146  0.000133
(80000.0, 107000.0]     196124  35503  160621  0.145028  0.003326
(107000.0, 10999200.0]  197202  31556  165646  0.293685  0.013093

_____________ Liczba żądanych binów: 7 (Faktycznie: 7) _____________


IV for annual_inc_bins = 0.0289


                         total    bad    good       WoE        IV
annual_inc_bins
(2399.999, 38880.0]     169615  41338  128277 -0.231990  0.008217
(38880.0, 50000.0]      202360  45727  156633 -0.133183  0.003143
(50000.0, 60000.0]      162998  35284  127714 -0.078038  0.000855
(60000.0, 71600.0]      143494  29435  114059 -0.009873  0.000012
(71600.0, 87000.0]      172176  33550  138626  0.054340  0.000421
(87000.0, 113200.0]     167000  29331  137669  0.181802  0.004400
(113200.0, 10999200.0]  169597  26971  142626  0.301057  0.011805

_____________ Liczba żądanych binów: 8 (Faktycznie: 8) _____________


IV for annual_inc_bins = 0.0291


                         total    bad    good       WoE        IV
annual_inc_bins
(2399.999, 36576.0]     148407  36390  112017 -0.240044  0.007715
(36576.0, 46906.75]     148403  34080  114323 -0.154085  0.003103
(46906.75, 55000.0]     152805  33425  119380 -0.091395  0.001104
(55000.0, 65000.0]      157070  33453  123617 -0.057356  0.000443
(65000.0, 76000.0]      135851  27169  108682  0.021944  0.000055
(76000.0, 92000.0]      152724  28843  123881  0.093049  0.001083
(92000.0, 120000.0]     157440  27271  130169  0.198604  0.004925
(120000.0, 10999200.0]  134540  21005  113535  0.322940  0.010701

_____________ Liczba żądanych binów: 9 (Faktycznie: 9) _____________


IV for annual_inc_bins = 0.0294


                         total    bad    good       WoE        IV
annual_inc_bins
(2399.999, 35000.0]     134463  33017  101446 -0.241898  0.007102
(35000.0, 45000.0]      150088  34709  115379 -0.163178  0.003529
(45000.0, 52000.0]      114051  25090   88961 -0.098677  0.000963
(52000.0, 60000.0]      136371  29533  106838 -0.078598  0.000726
(60000.0, 70000.0]      137243  28244  108999 -0.013947  0.000023
(70000.0, 80000.0]      121698  23984   97714  0.040251  0.000164
(80000.0, 96340.0]      129496  23980  105516  0.117235  0.001447
(96340.0, 122900.0]     131918  22480  109438  0.218323  0.004956
(122900.0, 10999200.0]  131912  20599  111313  0.322692  0.010477

In [20]:
check_num_bins(df, "tot_cur_bal")

Analiza zmiennej numerycznej: tot_cur_bal

_____________ Liczba żądanych binów: 2 (Faktycznie: 2) _____________


IV for tot_cur_bal_bins = 0.0271


                       total     bad    good       WoE        IV
tot_cur_bal_bins
(-0.001, 79535.5]     593620  136613  457007 -0.156847  0.012873
(79535.5, 5445012.0]  593620  105023  488597  0.172963  0.014195

_____________ Liczba żądanych binów: 3 (Faktycznie: 3) _____________


IV for tot_cur_bal_bins = 0.0325


                          total    bad    good       WoE        IV
tot_cur_bal_bins
(-0.001, 39627.0]        395752  88957  306795 -0.126369  0.005523
(39627.0, 163651.667]    395741  88119  307622 -0.114212  0.004495
(163651.667, 5445012.0]  395747  64560  331187  0.270690  0.022483

_____________ Liczba żądanych binów: 4 (Faktycznie: 4) _____________


IV for tot_cur_bal_bins = 0.0375


                        total    bad    good       WoE        IV
tot_cur_bal_bins
(29407.0, 79535.5]     296794  71172  225622 -0.210635  0.011783
(-0.001, 29407.0]      296826  65441  231385 -0.101463  0.002651
(79535.5, 209667.0]    296812  58391  238421  0.042478  0.000445
(209667.0, 5445012.0]  296808  46632  250176  0.315478  0.022582

_____________ Liczba żądanych binów: 5 (Faktycznie: 5) _____________


IV for tot_cur_bal_bins = 0.0386


                        total    bad    good       WoE        IV
tot_cur_bal_bins
(24172.0, 50729.0]     237447  56661  180786 -0.204170  0.008842
(50729.0, 128894.0]    237445  53693  183752 -0.134094  0.003739
(-0.001, 24172.0]      237454  51516  185938 -0.080878  0.001340
(128894.0, 242917.0]   237447  43292  194155  0.136289  0.003565
(242917.0, 5445012.0]  237447  36474  200973  0.342168  0.021073

_____________ Liczba żądanych binów: 6 (Faktycznie: 6) _____________


IV for tot_cur_bal_bins = 0.0400


                         total    bad    good       WoE        IV
tot_cur_bal_bins
(39627.0, 79535.5]      197868  47656  150212 -0.216359  0.008302
(20856.0, 39627.0]      197869  46590  151279 -0.186659  0.006128
(-0.001, 20856.0]       197883  42367  155516 -0.064021  0.000696
(79535.5, 163651.667]   197873  40463  157410 -0.005935  0.000006
(163651.667, 268936.0]  197874  34675  163199  0.184549  0.005368
(268936.0, 5445012.0]   197873  29885  167988  0.362131  0.019545

_____________ Liczba żądanych binów: 7 (Faktycznie: 7) _____________


IV for tot_cur_bal_bins = 0.0403


                           total    bad    good       WoE        IV
tot_cur_bal_bins
(33490.0, 56966.714]      169598  40906  128692 -0.218255  0.007245
(18457.0, 33490.0]        169612  39616  129996 -0.176130  0.004663
(56966.714, 113629.286]   169606  38585  131021 -0.141907  0.002998
(-0.001, 18457.0]         169607  35916  133691 -0.050053  0.000363
(113629.286, 188921.714]  169605  32279  137326  0.083538  0.000972
(188921.714, 290643.429]  169606  29019  140587  0.213471  0.006101
(290643.429, 5445012.0]   169606  25315  144291  0.376027  0.017983

_____________ Liczba żądanych binów: 8 (Faktycznie: 8) _____________


IV for tot_cur_bal_bins = 0.0412


                          total    bad    good       WoE        IV
tot_cur_bal_bins
(46108.0, 79535.5]       148400  35633  112767 -0.212349  0.005991
(29407.0, 46108.0]       148394  35539  112855 -0.208928  0.005794
(16667.875, 29407.0]     148421  34245  114176 -0.160201  0.003361
(-0.001, 16667.875]      148405  31196  117209 -0.040734  0.000210
(79535.5, 141967.375]    148405  31066  117339 -0.035450  0.000159
(141967.375, 209667.0]   148407  27325  121082  0.124260  0.001859
(209667.0, 308746.125]   148403  24781  123622  0.242744  0.006840
(308746.125, 5445012.0]  148405  21851  126554  0.392012  0.017015

_____________ Liczba żądanych binów: 9 (Faktycznie: 9) _____________


IV for tot_cur_bal_bins = 0.0417


                          total    bad    good       WoE        IV
tot_cur_bal_bins
(39627.0, 61036.778]     131910  31984   99926 -0.225208  0.006011
(26464.0, 39627.0]       131906  31263  100643 -0.195258  0.004481
(61036.778, 105270.0]    131919  30199  101720 -0.149988  0.002611
(15252.0, 26464.0]       131924  30157  101767 -0.148134  0.002546
(-0.001, 15252.0]        131922  27537  104385 -0.031849  0.000114
(105270.0, 163651.667]   131912  25936  105976  0.043175  0.000204
(163651.667, 227387.0]   131918  23725  108193  0.152979  0.002483
(227387.0, 324628.556]   131913  21610  110303  0.265665  0.007230
(324628.556, 5445012.0]  131916  19225  112691  0.404025  0.016004

#  delinq_2yrs and num_tl_90g_dpd_24m

In [21]:
bad_payers = df[df['target'] == 1]

delinq_2yrs_count = (bad_payers['delinq_2yrs'] > 0).sum()
num_tl_90g_count = (bad_payers['num_tl_90g_dpd_24m'] > 0).sum()

print(f"Osoby z Defaultem: {bad_payers["target"].sum()}")
print(f"Liczba osób z target=1, które miały min. jedno spóźnienie >30 dni: {delinq_2yrs_count}")
print(f"Liczba osób z target=1, które miały min. jedno spóźnienie >90 dni: {num_tl_90g_count}")

Osoby z Defaultem: 241636
Liczba osób z target=1, które miały min. jedno spóźnienie >30 dni: 51180
Liczba osób z target=1, które miały min. jedno spóźnienie >90 dni: 15714

In [22]:
check_num_bins(df, "delinq_2yrs")

Analiza zmiennej numerycznej: delinq_2yrs

_____________ Liczba żądanych binów: 2 (Faktycznie: 1) _____________


IV for delinq_2yrs_bins = 0.0000


                    total     bad    good       WoE            IV
delinq_2yrs_bins
(-0.001, 39.0]    1187240  241636  945604 -0.000002  2.373031e-12
Osiągnięto maksymalny podział dla wartości unikalnych przy 1 binach.
Zmienna o za niskiej wartości informacyjnej.

In [23]:
df['has_delinq_flag'] = (df['delinq_2yrs'] > 0).astype(int)
report = df.groupby('has_delinq_flag')['target'].agg(['count', 'mean']).rename(columns={'mean': 'default_rate'})
print(report)

                  count  default_rate
has_delinq_flag
0                952024      0.200054
1                235216      0.217587

In [24]:
print(calculate_woe(df, "has_delinq_flag"))

IV for has_delinq_flag = 0.0018


(                  total     bad    good       WoE        IV
has_delinq_flag
1                235216   51180  184036 -0.084616  0.001454
0                952024  190456  761568  0.021565  0.000371, np.float64(0.0018246538951403484))

In [25]:
df['num_tl_90g_dpd_24m_flag'] = (df['num_tl_90g_dpd_24m'] > 0).astype(int)
report = df.groupby('num_tl_90g_dpd_24m_flag')['target'].agg(['count', 'mean']).rename(columns={'mean': 'default_rate'})
print(report)

                           count  default_rate
num_tl_90g_dpd_24m_flag
0                        1118475      0.201991
1                          68765      0.228517

In [26]:
print(calculate_woe(df, "num_tl_90g_dpd_24m_flag"))

IV for num_tl_90g_dpd_24m_flag = 0.0014


(                           total     bad    good       WoE        IV
num_tl_90g_dpd_24m_flag
1                          68765   15714   53051 -0.147712  0.001319
0                        1118475  225922  892553  0.009503  0.000085, np.float64(0.0014039766748022028))

In [27]:
def check_interaction(df, col_to_check, segment_col='initial_list_status'):
    df_temp = df.copy()
    df_temp['has_flag'] = (df[col_to_check] > 0).astype(int)

    pivot = df_temp.pivot_table(
        values='target', 
        index=segment_col, 
        columns='has_flag', 
        aggfunc='mean'
    )
    
    pivot['diff'] = pivot[1] - pivot[0]
    pivot['relative_increase_%'] = (pivot['diff'] / pivot[0]) * 100
    
    print(f"--- Interakcja: {segment_col} vs {col_to_check} (Default Rate) ---")
    return pivot


check_interaction(df, 'num_tl_90g_dpd_24m')

--- Interakcja: initial_list_status vs num_tl_90g_dpd_24m (Default Rate) ---

has_flag                    0         1      diff  relative_increase_%
initial_list_status
f                    0.202988  0.222993  0.020006             9.855578
w                    0.201367  0.232206  0.030839            15.314880

In [28]:
check_interaction(df, 'delinq_2yrs')

--- Interakcja: initial_list_status vs delinq_2yrs (Default Rate) ---

has_flag                    0         1      diff  relative_increase_%
initial_list_status
f                    0.202064  0.212630  0.010566             5.229022
w                    0.198797  0.220784  0.021987            11.059956

Maybe inquiries are selected? Anyway both features are not usefull enough at least.

# earliest cr line

In [29]:
df["earliest_cr_line"].max()

'Sep-2015'

In [30]:
df['earliest_cr_line'] = pd.to_datetime(df['earliest_cr_line'], format='%b-%Y')
df['issue_d'] = pd.to_datetime(df['issue_d'], format='%b-%Y')

df['mo_sin_old_cr_line'] = (df['issue_d'].dt.year - df['earliest_cr_line'].dt.year) * 12 + \
                           (df['issue_d'].dt.month - df['earliest_cr_line'].dt.month)

print(df[['earliest_cr_line', 'issue_d', 'mo_sin_old_cr_line']].head())

  earliest_cr_line    issue_d  mo_sin_old_cr_line
0       2003-12-01 2018-12-01                 180
1       1995-04-01 2018-12-01                 284
2       2009-04-01 2018-12-01                 116
3       2004-03-01 2018-12-01                 177
4       2007-06-01 2018-12-01                 138

In [31]:
check_num_bins(df, "mo_sin_old_cr_line")

Analiza zmiennej numerycznej: mo_sin_old_cr_line

_____________ Liczba żądanych binów: 2 (Faktycznie: 2) _____________


IV for mo_sin_old_cr_line_bins = 0.0087


                          total     bad    good       WoE        IV
mo_sin_old_cr_line_bins
(35.999, 179.0]          599784  131050  468734 -0.089938  0.004195
(179.0, 999.0]           587456  110586  476870  0.097056  0.004527

_____________ Liczba żądanych binów: 3 (Faktycznie: 3) _____________


IV for mo_sin_old_cr_line_bins = 0.0106


                          total    bad    good       WoE        IV
mo_sin_old_cr_line_bins
(35.999, 150.0]          398713  89708  309005 -0.127598  0.005675
(150.0, 217.0]           395893  79601  316292  0.015243  0.000077
(217.0, 999.0]           392634  72327  320307  0.123686  0.004874

_____________ Liczba żądanych binów: 4 (Faktycznie: 4) _____________


IV for mo_sin_old_cr_line_bins = 0.0112


                          total    bad    good       WoE        IV
mo_sin_old_cr_line_bins
(35.999, 136.0]          300160  68560  231600 -0.147094  0.005709
(136.0, 179.0]           299624  62490  237134 -0.030778  0.000241
(179.0, 242.0]           291438  56646  234792  0.057481  0.000797
(242.0, 999.0]           296018  53940  242078  0.136989  0.004490

_____________ Liczba żądanych binów: 5 (Faktycznie: 5) _____________


IV for mo_sin_old_cr_line_bins = 0.0112


                          total    bad    good       WoE        IV
mo_sin_old_cr_line_bins
(35.999, 127.0]          242047  55273  186774 -0.146783  0.004584
(127.0, 161.0]           235990  51084  184906 -0.078022  0.001238
(161.0, 200.0]           238908  47755  191153  0.022591  0.000102
(200.0, 261.0]           234285  44928  189357  0.074173  0.001062
(261.0, 999.0]           236010  42596  193414  0.148672  0.004201

_____________ Liczba żądanych binów: 6 (Faktycznie: 6) _____________


IV for mo_sin_old_cr_line_bins = 0.0113


                          total    bad    good       WoE        IV
mo_sin_old_cr_line_bins
(35.999, 120.0]          201249  45942  155307 -0.146375  0.003790
(120.0, 150.0]           197464  43766  153698 -0.108267  0.002012
(150.0, 179.0]           201071  41342  159729 -0.012801  0.000028
(179.0, 217.0]           194822  38259  156563  0.044678  0.000323
(217.0, 277.0]           195563  36914  158649  0.093702  0.001406
(277.0, 999.0]           197071  35413  161658  0.154002  0.003758

_____________ Liczba żądanych binów: 7 (Faktycznie: 7) _____________


IV for mo_sin_old_cr_line_bins = 0.0115


                          total    bad    good       WoE        IV
mo_sin_old_cr_line_bins
(35.999, 114.0]          173097  39451  133646 -0.144265  0.003164
(114.0, 142.0]           168968  38140  130828 -0.131781  0.002568
(142.0, 166.0]           171509  36065  135444 -0.041166  0.000248
(166.0, 193.0]           167422  33509  133913  0.020974  0.000062
(193.0, 231.0]           169755  32945  136810  0.059351  0.000495
(231.0, 291.0]           167211  31147  136064  0.110004  0.001649
(291.0, 999.0]           169278  30379  138899  0.155591  0.003293

_____________ Liczba żądanych binów: 8 (Faktycznie: 8) _____________


IV for mo_sin_old_cr_line_bins = 0.0116


                          total    bad    good       WoE            IV
mo_sin_old_cr_line_bins
(35.999, 108.0]          149387  34191  115196 -0.149729  2.946195e-03
(108.0, 136.0]           150773  34369  116404 -0.144490  2.764954e-03
(136.0, 157.0]           149394  31895  117499 -0.060422  4.676354e-04
(157.0, 179.0]           150230  30595  119635 -0.000795  7.994057e-08
(179.0, 206.0]           146112  28760  117352  0.041788  2.122470e-04
(206.0, 242.0]           145326  27886  117440  0.073398  6.451088e-04
(242.0, 303.0]           148490  27345  121145  0.124049  1.854067e-03
(303.0, 999.0]           147528  26595  120933  0.150107  2.675800e-03

_____________ Liczba żądanych binów: 9 (Faktycznie: 9) _____________


IV for mo_sin_old_cr_line_bins = 0.0116


                          total    bad    good       WoE        IV
mo_sin_old_cr_line_bins
(35.999, 104.0]          135015  31028  103987 -0.155027  0.002859
(104.0, 131.0]           132287  30077  102210 -0.141134  0.002312
(131.0, 150.0]           131411  28603  102808 -0.085052  0.000821
(150.0, 169.0]           135294  28101  107193 -0.025579  0.000075
(169.0, 190.0]           130503  26153  104350  0.019381  0.000041
(190.0, 217.0]           130096  25347  104749  0.054500  0.000320
(217.0, 252.0]           129850  24757  105093  0.081331  0.000706
(252.0, 313.0]           132202  24012  108190  0.140928  0.002119
(313.0, 999.0]           130582  23558  107024  0.149180  0.002340
Zmienna o za niskiej wartości informacyjnej.

# open_acc / num_actv_bc_tl /  total_acc / total_rev_hi_lim

In [32]:
check_num_bins(df, "open_acc")

Analiza zmiennej numerycznej: open_acc

_____________ Liczba żądanych binów: 2 (Faktycznie: 2) _____________


IV for open_acc_bins = 0.0031


                 total     bad    good       WoE        IV
open_acc_bins
(11.0, 90.0]    520534  111274  409260 -0.062040  0.001719
(-0.001, 11.0]  666706  130362  536344  0.050066  0.001387

_____________ Liczba żądanych binów: 3 (Faktycznie: 3) _____________


IV for open_acc_bins = 0.0040


                total    bad    good       WoE        IV
open_acc_bins
(13.0, 90.0]   360203  77897  282306 -0.076792  0.001830
(9.0, 13.0]    358331  73862  284469 -0.015971  0.000077
(-0.001, 9.0]  468706  89877  378829  0.074247  0.002128

_____________ Liczba żądanych binów: 4 (Faktycznie: 4) _____________


IV for open_acc_bins = 0.0043


                total    bad    good       WoE        IV
open_acc_bins
(14.0, 90.0]   296255  64541  231714 -0.086194  0.001901
(11.0, 14.0]   224279  46733  177546 -0.029620  0.000167
(8.0, 11.0]    302798  61229  241569  0.008137  0.000017
(-0.001, 8.0]  363908  69133  294775  0.085783  0.002198

_____________ Liczba żądanych binów: 5 (Faktycznie: 5) _____________


IV for open_acc_bins = 0.0045


                total    bad    good       WoE        IV
open_acc_bins
(16.0, 90.0]   197457  43562  153895 -0.102314  0.001794
(12.0, 16.0]   237551  49908  187643 -0.040039  0.000325
(10.0, 12.0]   180790  37543  143247 -0.025318  0.000098
(7.0, 10.0]    307569  60944  246625  0.033516  0.000288
(-0.001, 7.0]  263873  49679  214194  0.096901  0.002027

_____________ Liczba żądanych binów: 6 (Faktycznie: 6) _____________


IV for open_acc_bins = 0.0046


                total    bad    good       WoE        IV
open_acc_bins
(16.0, 90.0]   197457  43562  153895 -0.102314  0.001794
(13.0, 16.0]   162746  34335  128411 -0.045331  0.000285
(11.0, 13.0]   160331  33377  126954 -0.028445  0.000110
(9.0, 11.0]    198000  40485  157515 -0.005811  0.000006
(7.0, 9.0]     204833  40198  164635  0.045513  0.000353
(-0.001, 7.0]  263873  49679  214194  0.096901  0.002027

_____________ Liczba żądanych binów: 7 (Faktycznie: 7) _____________


IV for open_acc_bins = 0.0048


                total    bad    good       WoE        IV
open_acc_bins
(17.0, 90.0]   160191  35659  124532 -0.113840  0.001808
(14.0, 17.0]   136064  28882  107182 -0.053094  0.000328
(12.0, 14.0]   138753  28929  109824 -0.030370  0.000109
(10.0, 12.0]   180790  37543  143247 -0.025318  0.000098
(8.0, 10.0]    207534  41490  166044  0.022400  0.000087
(6.0, 8.0]     189333  36614  152719  0.063767  0.000636
(-0.001, 6.0]  174575  32519  142056  0.109994  0.001721

_____________ Liczba żądanych binów: 8 (Faktycznie: 8) _____________


IV for open_acc_bins = 0.0048


                total    bad    good       WoE        IV
open_acc_bins
(18.0, 90.0]   129429  28990  100439 -0.121804  0.001676
(14.0, 18.0]   166826  35551  131275 -0.058076  0.000482
(12.0, 14.0]   138753  28929  109824 -0.030370  0.000109
(11.0, 12.0]    85526  17804   67722 -0.028424  0.000059
(9.0, 11.0]    198000  40485  157515 -0.005811  0.000006
(8.0, 9.0]     104798  20744   84054  0.034793  0.000106
(6.0, 8.0]     189333  36614  152719  0.063767  0.000636
(-0.001, 6.0]  174575  32519  142056  0.109994  0.001721

_____________ Liczba żądanych binów: 9 (Faktycznie: 9) _____________


IV for open_acc_bins = 0.0048


                total    bad    good       WoE        IV
open_acc_bins
(18.0, 90.0]   129429  28990  100439 -0.121804  0.001676
(15.0, 18.0]   113134  24228   88906 -0.064336  0.000402
(13.0, 15.0]   117640  24679   92961 -0.038179  0.000146
(11.0, 13.0]   160331  33377  126954 -0.028445  0.000110
(10.0, 11.0]    95264  19739   75525 -0.022543  0.000041
(9.0, 10.0]    102736  20746   81990  0.009834  0.000008
(7.0, 9.0]     204833  40198  164635  0.045513  0.000353
(6.0, 7.0]      89298  17160   72138  0.071586  0.000377
(-0.001, 6.0]  174575  32519  142056  0.109994  0.001721
Zmienna o za niskiej wartości informacyjnej.

In [33]:
check_num_bins(df, "num_actv_bc_tl")

Analiza zmiennej numerycznej: num_actv_bc_tl

_____________ Liczba żądanych binów: 2 (Faktycznie: 2) _____________


IV for num_actv_bc_tl_bins = 0.0081


                      total     bad    good       WoE        IV
num_actv_bc_tl_bins
(3.0, 35.0]          531142  116732  414410 -0.097419  0.004369
(-0.001, 3.0]        656098  124904  531194  0.083187  0.003730

_____________ Liczba żądanych binów: 3 (Faktycznie: 3) _____________


IV for num_actv_bc_tl_bins = 0.0099


                      total    bad    good       WoE        IV
num_actv_bc_tl_bins
(4.0, 35.0]          333143  75914  257229 -0.144030  0.006070
(2.0, 4.0]           452787  90695  362092  0.020001  0.000152
(-0.001, 2.0]        401310  75027  326283  0.105521  0.003646

_____________ Liczba żądanych binów: 4 (Faktycznie: 4) _____________


IV for num_actv_bc_tl_bins = 0.0107


                      total    bad    good       WoE        IV
num_actv_bc_tl_bins
(5.0, 35.0]          200803  47219  153584 -0.184947  0.006103
(3.0, 5.0]           330339  69513  260826 -0.042057  0.000498
(2.0, 3.0]           254788  49877  204911  0.048617  0.000500
(-0.001, 2.0]        401310  75027  326283  0.105521  0.003646

_____________ Liczba żądanych binów: 5 (Faktycznie: 5) _____________


IV for num_actv_bc_tl_bins = 0.0110


                      total    bad    good       WoE        IV
num_actv_bc_tl_bins
(5.0, 35.0]          200803  47219  153584 -0.184947  0.006103
(4.0, 5.0]           132340  28695  103645 -0.080155  0.000733
(3.0, 4.0]           197999  40818  157181 -0.016126  0.000044
(2.0, 3.0]           254788  49877  204911  0.048617  0.000500
(-0.001, 2.0]        401310  75027  326283  0.105521  0.003646

_____________ Liczba żądanych binów: 6 (Faktycznie: 5) _____________


IV for num_actv_bc_tl_bins = 0.0116


                      total    bad    good       WoE        IV
num_actv_bc_tl_bins
(6.0, 35.0]          118692  28934   89758 -0.232303  0.005766
(4.0, 6.0]           214451  46980  167471 -0.093311  0.001616
(3.0, 4.0]           197999  40818  157181 -0.016126  0.000044
(2.0, 3.0]           254788  49877  204911  0.048617  0.000500
(-0.001, 2.0]        401310  75027  326283  0.105521  0.003646
Osiągnięto maksymalny podział dla wartości unikalnych przy 5 binach.
Zmienna o za niskiej wartości informacyjnej.

In [34]:
check_num_bins(df, "total_acc")

Analiza zmiennej numerycznej: total_acc

_____________ Liczba żądanych binów: 2 (Faktycznie: 2) _____________


IV for total_acc_bins = 0.0012


                 total     bad    good       WoE        IV
total_acc_bins
(1.999, 23.0]   595002  124386  470616 -0.033742  0.000576
(23.0, 176.0]   592238  117250  474988  0.034587  0.000591

_____________ Liczba żądanych binów: 3 (Faktycznie: 3) _____________


IV for total_acc_bins = 0.0015


                 total    bad    good       WoE        IV
total_acc_bins
(1.999, 19.0]   425281  90095  335186 -0.050575  0.000930
(19.0, 29.0]    391188  78308  312880  0.020774  0.000141
(29.0, 176.0]   370771  73233  297538  0.037499  0.000434

_____________ Liczba żądanych binów: 4 (Faktycznie: 4) _____________


IV for total_acc_bins = 0.0017


                 total    bad    good       WoE            IV
total_acc_bins
(1.999, 16.0]   300134  64349  235785 -0.065798  1.115836e-03
(16.0, 23.0]    294868  60037  234831 -0.000493  6.026268e-08
(23.0, 32.0]    308937  61197  247740  0.033884  2.957617e-04
(32.0, 176.0]   283301  56053  227248  0.035346  2.950004e-04

_____________ Liczba żądanych binów: 5 (Faktycznie: 5) _____________


IV for total_acc_bins = 0.0018


                 total    bad    good       WoE        IV
total_acc_bins
(1.999, 15.0]   260553  56021  204532 -0.069400  0.001079
(15.0, 21.0]    250140  51483  198657 -0.014071  0.000042
(21.0, 26.0]    202446  40539  161907  0.020357  0.000070
(34.0, 176.0]   234688  46510  188178  0.033321  0.000217
(26.0, 34.0]    239413  47083  192330  0.042901  0.000366

_____________ Liczba żądanych binów: 6 (Faktycznie: 6) _____________


IV for total_acc_bins = 0.0018


                 total    bad    good       WoE        IV
total_acc_bins
(1.999, 14.0]   222870  48058  174812 -0.073096  0.001025
(14.0, 19.0]    202411  42037  160374 -0.025442  0.000111
(19.0, 23.0]    169721  34291  135430  0.009170  0.000012
(36.0, 176.0]   192929  38410  154519  0.027598  0.000123
(23.0, 29.0]    221467  44017  177450  0.029713  0.000163
(29.0, 36.0]    177842  34823  143019  0.048297  0.000344

_____________ Liczba żądanych binów: 7 (Faktycznie: 7) _____________


IV for total_acc_bins = 0.0018


                 total    bad    good       WoE        IV
total_acc_bins
(1.999, 13.0]   187135  40465  146670 -0.076653  0.000947
(13.0, 17.0]    154157  32343  121814 -0.038305  0.000193
(17.0, 21.0]    169401  34696  134705 -0.007939  0.000009
(21.0, 26.0]    202446  40539  161907  0.020357  0.000070
(38.0, 176.0]   157509  31492  126017  0.022280  0.000065
(26.0, 31.0]    163367  32157  131210  0.041766  0.000237
(31.0, 38.0]    153225  29944  123281  0.050733  0.000327

_____________ Liczba żądanych binów: 8 (Faktycznie: 8) _____________


IV for total_acc_bins = 0.0019


                 total    bad    good       WoE        IV
total_acc_bins
(1.999, 12.0]   153543  33161  120382 -0.075107  0.000746
(12.0, 16.0]    146591  31188  115403 -0.056006  0.000394
(16.0, 20.0]    167996  34480  133516 -0.010560  0.000016
(20.0, 23.0]    126872  25557  101315  0.012917  0.000018
(39.0, 176.0]   141975  28496  113479  0.017450  0.000036
(23.0, 27.0]    154474  30881  123593  0.022449  0.000065
(27.0, 32.0]    154463  30316  124147  0.045387  0.000264
(32.0, 39.0]    141326  27557  113769  0.053508  0.000335

_____________ Liczba żądanych binów: 9 (Faktycznie: 9) _____________


IV for total_acc_bins = 0.0019


                 total    bad    good       WoE        IV
total_acc_bins
(1.999, 12.0]   153543  33161  120382 -0.075107  0.000746
(12.0, 16.0]    146591  31188  115403 -0.056006  0.000394
(16.0, 19.0]    125147  25746   99401 -0.013523  0.000019
(19.0, 22.0]    127973  25937  102036  0.005249  0.000003
(40.0, 176.0]   127780  25647  102133  0.017443  0.000033
(22.0, 25.0]    122038  24459   97579  0.019257  0.000038
(25.0, 29.0]    141177  27912  113265  0.036269  0.000155
(29.0, 33.0]    112654  22153   90501  0.042980  0.000173
(33.0, 40.0]    130337  25433  104904  0.052592  0.000299
Zmienna o za niskiej wartości informacyjnej.

In [35]:
check_num_bins(df, "total_rev_hi_lim")

Analiza zmiennej numerycznej: total_rev_hi_lim

_____________ Liczba żądanych binów: 2 (Faktycznie: 2) _____________


IV for total_rev_hi_lim_bins = 0.0138


                        total     bad    good       WoE        IV
total_rev_hi_lim_bins
(-0.001, 24050.0]      593635  132098  461537 -0.113376  0.006643
(24050.0, 9999999.0]   593605  109538  484067  0.121557  0.007122

_____________ Liczba żądanych binów: 3 (Faktycznie: 3) _____________


IV for total_rev_hi_lim_bins = 0.0203


                         total    bad    good       WoE        IV
total_rev_hi_lim_bins
(-0.001, 17100.0]       397482  89519  307963 -0.128867  0.005772
(17100.0, 33659.667]    394011  84018  309993 -0.058877  0.001171
(33659.667, 9999999.0]  395747  68099  327648  0.206580  0.013359

_____________ Liczba żądanych binów: 4 (Faktycznie: 4) _____________


IV for total_rev_hi_lim_bins = 0.0234


                        total    bad    good       WoE        IV
total_rev_hi_lim_bins
(-0.001, 14000.0]      297256  67408  229848 -0.137742  0.004944
(14000.0, 24050.0]     296379  64690  231689 -0.088608  0.002012
(24050.0, 40600.0]     297267  61035  236232 -0.011031  0.000031
(40600.0, 9999999.0]   296338  48503  247835  0.266738  0.016368

_____________ Liczba żądanych binów: 5 (Faktycznie: 5) _____________


IV for total_rev_hi_lim_bins = 0.0249


                        total    bad    good       WoE        IV
total_rev_hi_lim_bins
(-0.001, 12200.0]      238258  54266  183992 -0.143404  0.004303
(12200.0, 19700.0]     238233  52613  185620 -0.103660  0.002223
(19700.0, 29300.0]     236672  50622  186050 -0.062769  0.000800
(29300.0, 46100.0]     236847  46637  190210  0.041335  0.000337
(46100.0, 9999999.0]   237230  37498  199732  0.308287  0.017275

_____________ Liczba żądanych binów: 6 (Faktycznie: 6) _____________


IV for total_rev_hi_lim_bins = 0.0263


                        total    bad    good       WoE        IV
total_rev_hi_lim_bins
(-0.001, 11000.0]      199982  45634  154348 -0.145842  0.003738
(11000.0, 17100.0]     197500  43885  153615 -0.111523  0.002137
(17100.0, 24050.0]     196153  42579  153574 -0.081579  0.001126
(24050.0, 33659.667]   197858  41439  156419 -0.036084  0.000219
(33659.667, 50700.0]   197983  37865  160118  0.077482  0.000978
(50700.0, 9999999.0]   197764  30234  167530  0.347790  0.018100

_____________ Liczba żądanych binów: 7 (Faktycznie: 7) _____________


IV for total_rev_hi_lim_bins = 0.0273


                        total    bad    good       WoE        IV
total_rev_hi_lim_bins
(-0.001, 10100.0]      171933  39391  132542 -0.151038  0.003452
(10100.0, 15300.0]     167574  37308  130266 -0.114030  0.001897
(15300.0, 20900.0]     171221  37560  133661 -0.095034  0.001339
(20900.0, 27700.0]     169019  36194  132825 -0.064262  0.000599
(27700.0, 37400.0]     169339  34710  134629 -0.008907  0.000011
(37400.0, 54700.0]     168959  31261  137698  0.118288  0.001922
(54700.0, 9999999.0]   169195  25212  143983  0.377967  0.018114

_____________ Liczba żądanych binów: 8 (Faktycznie: 8) _____________


IV for total_rev_hi_lim_bins = 0.0278


                        total    bad    good       WoE        IV
total_rev_hi_lim_bins
(-0.001, 9400.0]       150135  34647  115488 -0.160446  0.003410
(9400.0, 14000.0]      147121  32761  114360 -0.114290  0.001674
(14000.0, 18700.0]     149402  32864  116538 -0.098563  0.001258
(18700.0, 24050.0]     146977  31826  115151 -0.078442  0.000779
(24050.0, 30800.0]     148404  31470  116934 -0.051828  0.000341
(30800.0, 40600.0]     148863  29565  119298  0.030629  0.000117
(40600.0, 58200.0]     148092  26846  121246  0.143299  0.002453
(58200.0, 9999999.0]   148246  21657  126589  0.401206  0.017751

_____________ Liczba żądanych binów: 9 (Faktycznie: 9) _____________


IV for total_rev_hi_lim_bins = 0.0279


                        total    bad    good       WoE        IV
total_rev_hi_lim_bins
(-0.001, 8800.0]       132762  30699  102063 -0.163043  0.003116
(8800.0, 13000.0]      131893  29547  102346 -0.122026  0.001714
(13000.0, 17100.0]     132827  29273  103554 -0.100976  0.001175
(17100.0, 21500.0]     130277  28325  101952 -0.083647  0.000787
(21500.0, 26800.0]     132260  28505  103755 -0.072451  0.000597
(26800.0, 33659.667]   131474  27188  104286 -0.020044  0.000045
(33659.667, 43500.0]   132499  25742  106757  0.058025  0.000369
(43500.0, 61500.0]     131709  23479  108230  0.163744  0.002831
(61500.0, 9999999.0]   131539  18878  112661  0.421973  0.017307

In [36]:
df['data_gap_flag'] = df['num_actv_bc_tl'].isna().astype(int)
print(calculate_woe(df, 'data_gap_flag'))

IV for data_gap_flag = 0.0000


(                 total     bad    good       WoE            IV
data_gap_flag
0              1187240  241636  945604 -0.000002  2.373031e-12, np.float64(2.373030955705664e-12))

In [37]:
cols = ['num_actv_bc_tl', 'total_rev_hi_lim', 'mo_sin_old_rev_tl_op']

is_nan_df = df[cols].isna()

base_col = cols[0]
mask_base = is_nan_df[base_col]
base_count = mask_base.sum()

print(f"Liczba osób z NaN w '{base_col}': {base_count}")

for other_col in cols[1:]:
    overlap = (mask_base & is_nan_df[other_col]).sum()
    percent = (overlap / base_count) * 100
    print(f" -> Z tych osób, {overlap} ({percent:.2f}%) ma również NaN w '{other_col}'")

any_nan = is_nan_df.any(axis=1)
all_nan = is_nan_df.all(axis=1)
not_consistent = any_nan & ~all_nan

print(f"\nLiczba osób mających braki w sposób NIESPÓJNY: {not_consistent.sum()}")

if not_consistent.sum() > 0:
    print("Przykładowe rekordy z niespójnymi brakami:")
    print(df.loc[not_consistent, cols].head())

# It was 100%

Liczba osób z NaN w 'num_actv_bc_tl': 0
 -> Z tych osób, 0 (nan%) ma również NaN w 'total_rev_hi_lim'
 -> Z tych osób, 0 (nan%) ma również NaN w 'mo_sin_old_rev_tl_op'

Liczba osób mających braki w sposób NIESPÓJNY: 0

C:\Users\User\AppData\Local\Temp\ipykernel_29016\1001598212.py:13: RuntimeWarning: invalid value encountered in scalar divide
  percent = (overlap / base_count) * 100

In [38]:
missing_segment = df[df['num_actv_bc_tl'].isna()].copy()

print("Rozkład dat dla brakujących danych:")
print(missing_segment['issue_d'].value_counts().sort_index())

print("\nRozkład dat dla pełnych danych (procentowy):")
print(df[df['num_actv_bc_tl'].notna()]['issue_d'].value_counts().sort_index())


print("Cel kredytu w grupie z brakami:")
print(missing_segment['purpose'].value_counts(normalize=True))

print("\nStatus zatrudnienia w grupie z brakami:")
print(missing_segment['emp_length'].value_counts(normalize=True))

Rozkład dat dla brakujących danych:
Series([], Name: count, dtype: int64)

Rozkład dat dla pełnych danych (procentowy):
issue_d
2013-01-01     6872
2013-02-01     7561
2013-03-01     8273
2013-04-01     9419
2013-05-01    10350
              ...
2018-08-01     2467
2018-09-01     1605
2018-10-01     1372
2018-11-01      973
2018-12-01      735
Name: count, Length: 72, dtype: int64
Cel kredytu w grupie z brakami:
Series([], Name: proportion, dtype: float64)

Status zatrudnienia w grupie z brakami:
Series([], Name: proportion, dtype: float64)

# revol_util / bc_util

In [39]:
# Revol util has some numbers over 100, what makes it tricky
check_num_bins(df, "revol_util") #  to see how lower boundries behave

Analiza zmiennej numerycznej: revol_util

_____________ Liczba żądanych binów: 2 (Faktycznie: 3) _____________


IV for revol_util_bins = 0.0157


                  total     bad    good       WoE        IV
revol_util_bins
(52.0, 892.3]    592847  132705  460142 -0.120988  0.007572
nan                 679     132     547  0.054388  0.000002
(-0.001, 52.0]   593714  108799  484915  0.130076  0.008136

_____________ Liczba żądanych binów: 3 (Faktycznie: 4) _____________


IV for revol_util_bins = 0.0205


                  total    bad    good       WoE        IV
revol_util_bins
(63.9, 892.3]    395359  89897  305462 -0.141235  0.006921
(40.0, 63.9]     395221  83267  311954 -0.043592  0.000641
nan                 679    132     547  0.054388  0.000002
(-0.001, 40.0]   395981  68340  327641  0.203026  0.012926

_____________ Liczba żądanych binów: 4 (Faktycznie: 5) _____________


IV for revol_util_bins = 0.0229


                  total    bad    good       WoE        IV
revol_util_bins
(70.4, 892.3]    296542  67909  228633 -0.150447  0.005906
(52.0, 70.4]     296305  64796  231509 -0.091022  0.002124
(33.6, 52.0]     296514  59565  236949  0.016379  0.000067
nan                 679    132     547  0.054388  0.000002
(-0.001, 33.6]   297200  49234  247966  0.252308  0.014754

_____________ Liczba żądanych binów: 5 (Faktycznie: 6) _____________


IV for revol_util_bins = 0.0239


                  total    bad    good       WoE        IV
revol_util_bins
(74.7, 892.3]    236580  54574  182006 -0.159916  0.005338
(59.0, 74.7]     237758  52589  185169 -0.105636  0.002305
(45.0, 59.0]     235859  49859  186000 -0.047851  0.000461
nan                 679    132     547  0.054388  0.000002
(29.3, 45.0]     238876  46236  192640  0.062665  0.000775
(-0.001, 29.3]   237488  38246  199242  0.286079  0.014997

_____________ Liczba żądanych binów: 6 (Faktycznie: 7) _____________


IV for revol_util_bins = 0.0245


                  total    bad    good       WoE        IV
revol_util_bins
(77.8, 892.3]    197071  45581  151490 -0.163370  0.004645
(63.9, 77.8]     198288  44316  153972 -0.118974  0.002448
(52.0, 63.9]     197488  42808  154680 -0.079766  0.001083
(40.0, 52.0]     197733  40459  157274 -0.006700  0.000007
nan                 679    132     547  0.054388  0.000002
(26.2, 40.0]     197347  36990  160357  0.102353  0.001689
(-0.001, 26.2]   198634  31350  167284  0.310074  0.014625

_____________ Liczba żądanych binów: 7 (Faktycznie: 8) _____________


IV for revol_util_bins = 0.0248


                  total    bad    good       WoE        IV
revol_util_bins
(80.1, 892.3]    168819  39098  129721 -0.165086  0.004065
(67.6, 80.1]     169511  38038  131473 -0.124185  0.002283
(57.0, 67.6]     169607  37442  132165 -0.103143  0.001566
(47.0, 57.0]     169124  35716  133408 -0.046588  0.000313
(36.4, 47.0]     170148  33947  136201  0.024929  0.000088
nan                 679    132     547  0.054388  0.000002
(23.7, 36.4]     169573  30859  138714  0.138582  0.002631
(-0.001, 23.7]   169779  26404  143375  0.327541  0.013871

_____________ Liczba żądanych binów: 8 (Faktycznie: 9) _____________


IV for revol_util_bins = 0.0251


                  total    bad    good       WoE        IV
revol_util_bins
(82.0, 892.3]    147472  34261  113211 -0.169156  0.003733
(70.4, 82.0]     149070  33648  115422 -0.131761  0.002265
(60.9, 70.4]     147049  32585  114464 -0.107994  0.001491
(52.0, 60.9]     149256  32211  117045 -0.074152  0.000706
(43.1, 52.0]     148258  30594  117664 -0.017374  0.000038
(33.6, 43.1]     148256  28971  119285  0.050816  0.000318
nan                 679    132     547  0.054388  0.000002
(21.7, 33.6]     148510  26426  122084  0.165955  0.003276
(-0.001, 21.7]   148690  22808  125882  0.343824  0.013317

_____________ Liczba żądanych binów: 9 (Faktycznie: 10) _____________


IV for revol_util_bins = 0.0254


                  total    bad    good       WoE        IV
revol_util_bins
(83.5, 892.3]    131502  30614  100888 -0.171849  0.003438
(72.8, 83.5]     131004  29756  101248 -0.139861  0.002248
(63.9, 72.8]     132853  29527  103326 -0.111820  0.001446
(55.9, 63.9]     131884  28834  103050 -0.090745  0.000939
(48.1, 55.9]     131315  27740  103575 -0.046984  0.000248
(40.0, 48.1]     132022  26693  105329  0.008282  0.000008
nan                 679    132     547  0.054388  0.000002
(31.3, 40.0]     131299  25190  106109  0.073613  0.000586
(20.0, 31.3]     132676  23085  109591  0.193164  0.003932
(-0.001, 20.0]   132006  20065  111941  0.354583  0.012531

In [40]:
df['revol_util'] = df['revol_util'].fillna(df['revol_util'].median())

bins = [-0.001, 20, 35, 50, 65, 85, 100, np.inf]
labels = ['0-3', '20-35', '35-50', '50-65', '50-85', '85-100', '100+']

df['revol_util_custom'] = pd.cut(df['revol_util'], bins=bins, labels=labels)
print(calculate_woe(df, 'revol_util_custom'))

IV for revol_util_custom = 0.0249


(                    total    bad    good       WoE        IV
revol_util_custom
100+                 4459   1199    3260 -0.364416  0.000552
85-100             111394  25835   85559 -0.166929  0.002744
50-85              261932  58875  203057 -0.126327  0.003653
50-65              249266  53926  195340 -0.077269  0.001282
35-50              241866  48568  193298  0.016869  0.000058
20-35              186317  33168  153149  0.165423  0.004085
0-3                132006  20065  111941  0.354583  0.012531, np.float64(0.024905170561991593))

C:\Users\User\AppData\Local\Temp\ipykernel_29016\1323708227.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  stats = df.groupby(feature)[target].agg(["count", "sum"])

In [41]:
check_num_bins(df, "bc_util")

Analiza zmiennej numerycznej: bc_util

_____________ Liczba żądanych binów: 2 (Faktycznie: 3) _____________


IV for bc_util_bins = 0.0195


                 total     bad    good       WoE        IV
bc_util_bins
(63.0, 339.6]   586566  132667  453899 -0.134362  0.009275
nan              13008    2741   10267 -0.043913  0.000021
(-0.001, 63.0]  587666  106228  481438  0.146795  0.010204

_____________ Liczba żądanych binów: 3 (Faktycznie: 4) _____________


IV for bc_util_bins = 0.0248


                 total    bad    good       WoE        IV
bc_util_bins
(77.8, 339.6]   390976  91324  299652 -0.176187  0.010757
nan              13008   2741   10267 -0.043913  0.000021
(47.0, 77.8]    391627  80513  311114 -0.012655  0.000053
(-0.001, 47.0]  391629  67058  324571  0.212549  0.013970

_____________ Liczba żądanych binów: 4 (Faktycznie: 5) _____________


IV for bc_util_bins = 0.0273


                 total    bad    good       WoE        IV
bc_util_bins
(84.7, 339.6]   293057  70082  222975 -0.207003  0.011226
(63.0, 84.7]    293509  62585  230924 -0.058834  0.000871
nan              13008   2741   10267 -0.043913  0.000021
(38.3, 63.0]    293368  57499  235869  0.047111  0.000541
(-0.001, 38.3]  294298  48729  245569  0.252904  0.014676

_____________ Liczba żądanych binów: 5 (Faktycznie: 6) _____________


IV for bc_util_bins = 0.0289


                 total    bad    good       WoE        IV
bc_util_bins
(88.6, 339.6]   234243  56983  177260 -0.229533  0.011102
(72.0, 88.6]    234579  51100  183479 -0.086083  0.001502
nan              13008   2741   10267 -0.043913  0.000021
(53.7, 72.0]    234629  48414  186215 -0.017286  0.000059
(32.5, 53.7]    235472  44355  191117  0.096260  0.001785
(-0.001, 32.5]  235309  38043  197266  0.281434  0.014402

_____________ Liczba żądanych binów: 6 (Faktycznie: 7) _____________


IV for bc_util_bins = 0.0290


                 total    bad    good       WoE        IV
bc_util_bins
(91.0, 339.6]   195132  48068  147064 -0.246147  0.010684
(77.8, 91.0]    195844  43256  152588 -0.103794  0.001832
(63.0, 77.8]    195590  41343  154247 -0.047748  0.000381
nan              13008   2741   10267 -0.043913  0.000021
(47.0, 63.0]    196037  39170  156867  0.023086  0.000087
(28.3, 47.0]    195436  35713  159723  0.133524  0.002819
(-0.001, 28.3]  196193  31345  164848  0.295565  0.013185

_____________ Liczba żądanych binów: 7 (Faktycznie: 8) _____________


IV for bc_util_bins = 0.0292


                 total    bad    good       WoE        IV
bc_util_bins
(92.7, 339.6]   166589  41459  125130 -0.259751  0.010195
(81.8, 92.7]    168595  37711  130884 -0.120041  0.002119
(69.5, 81.8]    167270  35929  131341 -0.068149  0.000668
nan              13008   2741   10267 -0.043913  0.000021
(56.4, 69.5]    167712  34679  133033 -0.019939  0.000056
(42.1, 56.4]    168131  32678  135453  0.057520  0.000461
(25.1, 42.1]    167473  29665  137808  0.171489  0.003939
(-0.001, 25.1]  168462  26774  141688  0.301790  0.011780

_____________ Liczba żądanych binów: 8 (Faktycznie: 9) _____________


IV for bc_util_bins = 0.0295


                 total    bad    good       WoE        IV
bc_util_bins
(93.8, 339.6]   146704  36746  109958 -0.268331  0.009604
(84.7, 93.8]    146353  33336  113017 -0.143502  0.002647
(74.2, 84.7]    146418  31691  114727 -0.077880  0.000765
nan              13008   2741   10267 -0.043913  0.000021
(63.0, 74.2]    147091  30894  116197 -0.039678  0.000197
(51.2, 63.0]    146985  29630  117355  0.012012  0.000018
(38.3, 51.2]    146383  27869  118514  0.083111  0.000831
(22.5, 38.3]    146973  25498  121475  0.196702  0.004512
(-0.001, 22.5]  147325  23231  124094  0.311143  0.010918

_____________ Liczba żądanych binów: 9 (Faktycznie: 10) _____________


IV for bc_util_bins = 0.0298


                 total    bad    good       WoE        IV
bc_util_bins
(94.7, 339.6]   129527  32725   96802 -0.279873  0.009253
(86.9, 94.7]    130929  30158  100771 -0.158003  0.002882
(77.8, 86.9]    130520  28441  102079 -0.086489  0.000843
(68.0, 77.8]    130819  27819  103000 -0.055395  0.000344
nan              13008   2741   10267 -0.043913  0.000021
(57.9, 68.0]    129947  26935  103012 -0.022986  0.000058
(47.0, 57.9]    130861  25759  105102  0.041741  0.000190
(35.1, 47.0]    130420  24386  106034  0.105343  0.001181
(20.4, 35.1]    130060  22049  108011  0.224556  0.005159
(-0.001, 20.4]  131149  20623  110526  0.314433  0.009916

In [42]:
df['bc_util'] = df['bc_util'].fillna(df['bc_util'].median())

bins = [-0.001, 20, 35, 50, 65, 85, 100, np.inf]
labels = ['0-20', '20-35', '35-50', '50-65', '50-85', '85-100', '100+']

df['bc_util_custom'] = pd.cut(df['bc_util'], bins=bins, labels=labels)
print(calculate_woe(df, 'bc_util_custom'))

IV for bc_util_custom = 0.0290


(                 total    bad    good       WoE        IV
bc_util_custom
100+             19486   5351   14135 -0.393079  0.002830
85-100          268677  63627  205050 -0.194181  0.009024
50-85           272778  58308  214470 -0.061967  0.000898
50-65           199741  40507  159234  0.004499  0.000003
35-50           166363  31340  135023  0.096146  0.001259
20-35           131903  22324  109579  0.226574  0.005323
0-20            128292  20179  108113  0.314123  0.009682, np.float64(0.029018826242077748))

C:\Users\User\AppData\Local\Temp\ipykernel_29016\1323708227.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  stats = df.groupby(feature)[target].agg(["count", "sum"])

In [43]:
check_num_bins(df, "bc_util")

Analiza zmiennej numerycznej: bc_util

_____________ Liczba żądanych binów: 2 (Faktycznie: 2) _____________


IV for bc_util_bins = 0.0191


                 total     bad    good       WoE        IV
bc_util_bins
(63.0, 339.6]   586566  132667  453899 -0.134362  0.009275
(-0.001, 63.0]  600674  108969  491705  0.142421  0.009831

_____________ Liczba żądanych binów: 3 (Faktycznie: 3) _____________


IV for bc_util_bins = 0.0247


                 total    bad    good       WoE        IV
bc_util_bins
(77.5, 339.6]   394981  92209  302772 -0.175473  0.010777
(47.4, 77.5]    396214  81503  314711 -0.013381  0.000060
(-0.001, 47.4]  396045  67924  328121  0.210596  0.013877

_____________ Liczba żądanych binów: 4 (Faktycznie: 4) _____________


IV for bc_util_bins = 0.0272


                 total    bad    good       WoE        IV
bc_util_bins
(84.5, 339.6]   295869  70681  225188 -0.205637  0.011180
(63.0, 84.5]    290697  61986  228711 -0.058847  0.000863
(38.6, 63.0]    303237  59683  243554  0.041894  0.000443
(-0.001, 38.6]  297437  49286  248151  0.251998  0.014731

_____________ Liczba żądanych binów: 5 (Faktycznie: 5) _____________


IV for bc_util_bins = 0.0288


                 total    bad    good       WoE        IV
bc_util_bins
(88.4, 339.6]   237170  57667  179503 -0.228890  0.011176
(71.6, 88.4]    237421  51650  185771 -0.084374  0.001459
(54.1, 71.6]    236673  48837  187836 -0.017318  0.000060
(32.8, 54.1]    237872  44950  192922  0.092335  0.001662
(-0.001, 32.8]  238104  38532  199572  0.280284  0.014459

_____________ Liczba żądanych binów: 6 (Faktycznie: 6) _____________


IV for bc_util_bins = 0.0290


                 total    bad    good       WoE        IV
bc_util_bins
(90.9, 339.6]   197595  48721  148874 -0.247408  0.010934
(77.5, 90.9]    197386  43488  153898 -0.100595  0.001733
(63.0, 77.5]    191585  40458  151127 -0.046544  0.000354
(47.4, 63.0]    204629  41045  163584  0.018257  0.000057
(28.5, 47.4]    198148  36267  161881  0.131551  0.002776
(-0.001, 28.5]  197897  31657  166240  0.294069  0.013171

_____________ Liczba żądanych binów: 7 (Faktycznie: 7) _____________


IV for bc_util_bins = 0.0293


                 total    bad    good       WoE        IV
bc_util_bins
(92.6, 339.6]   168343  41840  126503 -0.257986  0.010158
(81.6, 92.6]    169536  37947  131589 -0.120908  0.002162
(69.0, 81.6]    170784  36625  134159 -0.066107  0.000641
(56.8, 69.0]    169728  35152  134576 -0.021954  0.000069
(42.5, 56.8]    168673  32877  135796  0.053977  0.000407
(25.3, 42.5]    170075  30162  139913  0.170034  0.003934
(-0.001, 25.3]  170101  27033  143068  0.301855  0.011900

_____________ Liczba żądanych binów: 8 (Faktycznie: 8) _____________


IV for bc_util_bins = 0.0295


                 total    bad    good       WoE        IV
bc_util_bins
(93.8, 339.6]   146704  36746  109958 -0.268331  0.009604
(84.5, 93.8]    149165  33935  115230 -0.141919  0.002637
(73.8, 84.5]    149339  32396  116943 -0.080751  0.000840
(63.0, 73.8]    141358  29590  111768 -0.035415  0.000151
(51.6, 63.0]    155333  31470  123863  0.005738  0.000004
(38.6, 51.6]    147904  28213  119691  0.080726  0.000792
(22.7, 38.6]    148624  25801  122823  0.195924  0.004528
(-0.001, 22.7]  148813  23485  125328  0.310164  0.010963

_____________ Liczba żądanych binów: 9 (Faktycznie: 9) _____________


IV for bc_util_bins = 0.0298


                 total    bad    good       WoE        IV
bc_util_bins
(94.6, 339.6]   131404  33178   98226 -0.279017  0.009328
(86.7, 94.6]    131919  30368  101551 -0.157231  0.002875
(77.5, 86.7]    131658  28663  102995 -0.085331  0.000828
(67.6, 77.5]    132491  28153  104338 -0.054423  0.000336
(58.3, 67.6]    131941  27336  104605 -0.022418  0.000056
(47.4, 58.3]    131782  26014  105768  0.038207  0.000160
(35.4, 47.4]    131930  24708  107222  0.103367  0.001151
(20.6, 35.4]    131508  22360  109148  0.221022  0.005059
(-0.001, 20.6]  132607  20856  111751  0.314221  0.010013

# inq

In [44]:
# check_num_bins(df[df["issue_d"].dt.year > 2016], "inq_fi")
df_new = df[df["issue_d"].dt.year > 2016].copy()

bins = [-0.001, 1, 5, 20, np.inf]
labels = ['0-1', '1-5', '5-20', '20+']

df_new['inq_fi_binned'] = pd.cut(df_new['inq_fi'], bins=bins, labels=labels)

print(calculate_woe(df_new, "inq_fi_binned"))

IV for inq_fi_binned = 0.0016


(                total    bad    good       WoE        IV
inq_fi_binned
5-20             4595   1133    3462 -0.225788  0.001327
1-5             50275  10565   39710 -0.018447  0.000091
0-1            133288  27271  106017  0.015293  0.000165
20+                 8      1       7  0.266969  0.000003, np.float64(0.0015868414849138815))

C:\Users\User\AppData\Local\Temp\ipykernel_29016\1323708227.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  stats = df.groupby(feature)[target].agg(["count", "sum"])

Don't mind total, wont change anything

In [45]:
check_num_bins(df, "inq_last_6mths")

Analiza zmiennej numerycznej: inq_last_6mths

_____________ Liczba żądanych binów: 2 (Faktycznie: 2) _____________


IV for inq_last_6mths_bins = 0.0000


                       total     bad    good       WoE            IV
inq_last_6mths_bins
nan                        1       0       1 -0.265779  1.283555e-07
(-0.001, 6.0]        1187239  241636  945603 -0.000003  6.749550e-12

_____________ Liczba żądanych binów: 3 (Faktycznie: 3) _____________


IV for inq_last_6mths_bins = 0.0177


                       total     bad    good       WoE            IV
inq_last_6mths_bins
(1.0, 6.0]            179582   46058  133524 -0.300019  1.482260e-02
nan                        1       0       1 -0.265779  1.283555e-07
(-0.001, 1.0]        1007657  195578  812079  0.059245  2.926787e-03

_____________ Liczba żądanych binów: 4 (Faktycznie: 3) _____________


IV for inq_last_6mths_bins = 0.0177


                       total     bad    good       WoE            IV
inq_last_6mths_bins
(1.0, 6.0]            179582   46058  133524 -0.300019  1.482260e-02
nan                        1       0       1 -0.265779  1.283555e-07
(-0.001, 1.0]        1007657  195578  812079  0.059245  2.926787e-03
Osiągnięto maksymalny podział dla wartości unikalnych przy 3 binach.
Zmienna o za niskiej wartości informacyjnej.

In [46]:
bins = [-0.001, 0.001, 1, 3, np.inf]
labels = ['0', '1', '2-3', '3+']

df['inq_fi_6m_binned'] = pd.cut(df['inq_last_6mths'], bins=bins, labels=labels)

print(calculate_woe(df, "inq_fi_6m_binned"))

IV for inq_fi_6m_binned = 0.0277


(                   total     bad    good       WoE        IV
inq_fi_6m_binned
3+                 18309    5229   13080 -0.447583  0.003495
2-3               161273   40829  120444 -0.282606  0.011756
1                 323968   70845  253123 -0.091014  0.002321
0                 683689  124733  558956  0.135502  0.010150, np.float64(0.02772250860928641))

C:\Users\User\AppData\Local\Temp\ipykernel_29016\1323708227.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  stats = df.groupby(feature)[target].agg(["count", "sum"])

In [47]:
bins = [-0.001, 0.001, np.inf]
labels = ['0', '1+']

df['inq_fi_6m_binned_2'] = pd.cut(df['inq_last_6mths'], bins=bins, labels=labels)

print(calculate_woe(df, "inq_fi_6m_binned_2")) # Leave bins, flag not worthy

IV for inq_fi_6m_binned_2 = 0.0228


(                     total     bad    good       WoE        IV
inq_fi_6m_binned_2
1+                  503550  116903  386647 -0.168226  0.012602
0                   683689  124733  558956  0.135502  0.010150, np.float64(0.022751854677573978))

C:\Users\User\AppData\Local\Temp\ipykernel_29016\1323708227.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  stats = df.groupby(feature)[target].agg(["count", "sum"])

# Chargeoff

In [48]:
df['has_recent_chargeoff'] = np.where(df['chargeoff_within_12_mths'] > 0, 1, 0)
calculate_woe(df, "has_recent_chargeoff") # arent the same as "bad", changes nothing

IV for has_recent_chargeoff = 0.0000

(                        total     bad    good       WoE            IV
 has_recent_chargeoff
 1                       10316    2220    8096 -0.070692  4.433726e-05
 0                     1176924  239416  937508  0.000630  3.929989e-07,
 np.float64(4.4730256163226726e-05))

# mo_sin_old_rev_tl_op

In [49]:
df["mo_sin_old_rev_tl_op"].isna().sum()

np.int64(0)

In [50]:
check_num_bins(df, "mo_sin_old_rev_tl_op")

Analiza zmiennej numerycznej: mo_sin_old_rev_tl_op

_____________ Liczba żądanych binów: 2 (Faktycznie: 2) _____________


IV for mo_sin_old_rev_tl_op_bins = 0.0151


                            total     bad    good       WoE        IV
mo_sin_old_rev_tl_op_bins
(1.999, 164.0]             594370  132786  461584 -0.118469  0.007273
(164.0, 852.0]             592870  108850  484020  0.127760  0.007843

_____________ Liczba żądanych binów: 3 (Faktycznie: 3) _____________


IV for mo_sin_old_rev_tl_op_bins = 0.0189


                            total    bad    good       WoE        IV
mo_sin_old_rev_tl_op_bins
(1.999, 133.0]             402231  93881  308350 -0.175188  0.010938
(133.0, 203.0]             390452  76738  313714  0.043688  0.000620
(203.0, 852.0]             394557  71017  323540  0.152007  0.007334

_____________ Liczba żądanych binów: 4 (Faktycznie: 4) _____________


IV for mo_sin_old_rev_tl_op_bins = 0.0198


                            total    bad    good       WoE        IV
mo_sin_old_rev_tl_op_bins
(1.999, 117.0]             297364  70910  226454 -0.203266  0.010972
(117.0, 164.0]             297006  61876  235130 -0.029391  0.000218
(164.0, 231.0]             299220  56736  242484  0.088129  0.001906
(231.0, 852.0]             293650  52114  241536  0.169186  0.006726

_____________ Liczba żądanych binów: 5 (Faktycznie: 5) _____________


IV for mo_sin_old_rev_tl_op_bins = 0.0206


                            total    bad    good       WoE        IV
mo_sin_old_rev_tl_op_bins
(1.999, 107.0]             241139  58287  182852 -0.221099  0.010579
(107.0, 145.0]             238241  51703  186538 -0.081279  0.001358
(145.0, 186.0]             235547  45919  189628  0.053786  0.000565
(186.0, 250.0]             235681  44009  191672  0.106991  0.002200
(250.0, 852.0]             236632  41718  194914  0.177225  0.005933

_____________ Liczba żądanych binów: 6 (Faktycznie: 6) _____________


IV for mo_sin_old_rev_tl_op_bins = 0.0215


                            total    bad    good       WoE        IV
mo_sin_old_rev_tl_op_bins
(1.999, 98.0]              197884  48743  149141 -0.246068  0.010827
(98.0, 133.0]              204347  45138  159209 -0.103906  0.001916
(133.0, 164.0]             192139  38905  153234  0.006442  0.000007
(164.0, 203.0]             198313  37833  160480  0.080586  0.001059
(203.0, 266.0]             197238  36461  160777  0.119373  0.002284
(266.0, 852.0]             197319  34556  162763  0.185311  0.005396

_____________ Liczba żądanych binów: 7 (Faktycznie: 7) _____________


IV for mo_sin_old_rev_tl_op_bins = 0.0221


                            total    bad    good       WoE        IV
mo_sin_old_rev_tl_op_bins
(1.999, 92.0]              172717  43238  129479 -0.267600  0.011243
(92.0, 124.0]              169911  37787  132124 -0.112625  0.001876
(124.0, 150.0]             167457  35105  132352 -0.037280  0.000198
(150.0, 179.0]             168476  32755  135721  0.057143  0.000456
(179.0, 218.0]             171132  32491  138641  0.086522  0.001051
(218.0, 281.0]             169107  30813  138294  0.137041  0.002567
(281.0, 852.0]             168440  29447  138993  0.187427  0.004709

_____________ Liczba żądanych binów: 8 (Faktycznie: 8) _____________


IV for mo_sin_old_rev_tl_op_bins = 0.0227


                            total    bad    good       WoE        IV
mo_sin_old_rev_tl_op_bins
(1.999, 86.0]              150316  38317  111999 -0.291804  0.011711
(86.0, 117.0]              147048  32593  114455 -0.108318  0.001500
(117.0, 140.0]             150321  32431  117890 -0.073765  0.000704
(140.0, 164.0]             146685  29445  117240  0.017295  0.000037
(164.0, 192.0]             150175  28801  121374  0.074062  0.000679
(192.0, 231.0]             149045  27935  121110  0.102414  0.001277
(231.0, 293.0]             145616  26199  119417  0.152494  0.002724
(293.0, 852.0]             148034  25915  122119  0.185767  0.004067

_____________ Liczba żądanych binów: 9 (Faktycznie: 9) _____________


IV for mo_sin_old_rev_tl_op_bins = 0.0233


                            total    bad    good       WoE        IV
mo_sin_old_rev_tl_op_bins
(1.999, 81.0]              133725  34647   99078 -0.313705  0.012112
(81.0, 112.0]              134121  29670  104451 -0.105822  0.001305
(112.0, 133.0]             134385  29564  104821 -0.098707  0.001135
(133.0, 153.0]             126406  25974  100432 -0.012021  0.000015
(153.0, 176.0]             133683  25938  107745  0.059652  0.000394
(176.0, 203.0]             130363  24826  105537  0.082763  0.000734
(203.0, 241.0]             132149  24568  107581  0.112392  0.001359
(241.0, 304.0]             131975  23517  108458  0.164231  0.002853
(304.0, 852.0]             130433  22932  107501  0.180558  0.003391

# num_tl_op_past_12m

In [51]:
print(df[df["num_tl_op_past_12m"] == 0]["num_tl_op_past_12m"].sum())
print(df[df["num_tl_op_past_12m"].isna()]["num_tl_op_past_12m"].sum())

0.0
0.0

In [52]:
check_num_bins(df, "num_tl_op_past_12m")

Analiza zmiennej numerycznej: num_tl_op_past_12m

_____________ Liczba żądanych binów: 2 (Faktycznie: 2) _____________


IV for num_tl_op_past_12m_bins = 0.0343


                          total     bad    good       WoE        IV
num_tl_op_past_12m_bins
(2.0, 32.0]              428472  104540  323932 -0.233431  0.021025
(-0.001, 2.0]            758768  137096  621672  0.147337  0.013270

_____________ Liczba żądanych binów: 3 (Faktycznie: 3) _____________


IV for num_tl_op_past_12m_bins = 0.0418


                          total    bad    good       WoE        IV
num_tl_op_past_12m_bins
(3.0, 32.0]              232850  60382  172468 -0.314876  0.021254
(1.0, 3.0]               464651  98285  366366 -0.048634  0.000939
(-0.001, 1.0]            489739  82969  406770  0.225385  0.019564

_____________ Liczba żądanych binów: 4 (Faktycznie: 4) _____________


IV for num_tl_op_past_12m_bins = 0.0438


                          total    bad    good       WoE        IV
num_tl_op_past_12m_bins
(3.0, 32.0]              232850  60382  172468 -0.314876  0.021254
(2.0, 3.0]               195622  44158  151464 -0.131826  0.002975
(1.0, 2.0]               269029  54127  214902  0.014451  0.000047
(-0.001, 1.0]            489739  82969  406770  0.225385  0.019564

_____________ Liczba żądanych binów: 5 (Faktycznie: 4) _____________


IV for num_tl_op_past_12m_bins = 0.0438


                          total    bad    good       WoE        IV
num_tl_op_past_12m_bins
(3.0, 32.0]              232850  60382  172468 -0.314876  0.021254
(2.0, 3.0]               195622  44158  151464 -0.131826  0.002975
(1.0, 2.0]               269029  54127  214902  0.014451  0.000047
(-0.001, 1.0]            489739  82969  406770  0.225385  0.019564
Osiągnięto maksymalny podział dla wartości unikalnych przy 4 binach.

# pct_tl_nvr_dlq

In [56]:
df[df["pct_tl_nvr_dlq"].isna()]["pct_tl_nvr_dlq"].sum()

np.float64(0.0)

In [57]:
check_num_bins(df, "pct_tl_nvr_dlq")

Analiza zmiennej numerycznej: pct_tl_nvr_dlq

_____________ Liczba żądanych binów: 2 (Faktycznie: 3) _____________


IV for pct_tl_nvr_dlq_bins = 0.0011


                      total     bad    good       WoE        IV
pct_tl_nvr_dlq_bins
(-0.001, 97.9]       594544  124223  470321 -0.033057  0.000553
(97.9, 100.0]        592542  117391  475151  0.033728  0.000562
nan                     154      22     132  0.408676  0.000019

_____________ Liczba żądanych binów: 3 (Faktycznie: 3) _____________


IV for pct_tl_nvr_dlq_bins = 0.0012


                      total     bad    good       WoE        IV
pct_tl_nvr_dlq_bins
(-0.001, 94.0]       399570   84500  315070 -0.048352  0.000798
(94.0, 100.0]        787516  157114  630402  0.024992  0.000411
nan                     154      22     132  0.408676  0.000019

_____________ Liczba żądanych binów: 4 (Faktycznie: 4) _____________


IV for pct_tl_nvr_dlq_bins = 0.0012


                      total     bad    good       WoE        IV
pct_tl_nvr_dlq_bins
(-0.001, 91.3]       299002   62978  236024 -0.043249  0.000477
(91.3, 97.9]         295542   61245  234297 -0.022690  0.000129
(97.9, 100.0]        592542  117391  475151  0.033728  0.000562
nan                     154      22     132  0.408676  0.000019

_____________ Liczba żądanych binów: 5 (Faktycznie: 4) _____________


IV for pct_tl_nvr_dlq_bins = 0.0014


                      total     bad    good       WoE        IV
pct_tl_nvr_dlq_bins
(-0.001, 89.1]       237675   50171  187504 -0.046036  0.000430
(89.1, 95.5]         237236   50019  187217 -0.044533  0.000402
(95.5, 100.0]        712175  141424  570751  0.030796  0.000564
nan                     154      22     132  0.408676  0.000019
Osiągnięto maksymalny podział dla wartości unikalnych przy 4 binach.
Zmienna o za niskiej wartości informacyjnej.

# Features to keep

- loan_amnt
- home_ownership
- dti
- annual_inc
- tot_cur_bal
- total_rev_hi_lim
- revol_util
- bc_util
- inq_last_6mths
- mo_sin_old_rev_tl_op
- num_tl_op_past_12m